#!/bin/sh

#Specify a partition
#SBATCH --partition=short
# Request nodes
#SBATCH --nodes=1
# Request some processor cores
#SBATCH --ntasks=1
# Request 3 cores per task
#SBATCH --cpus-per-task=8
# Request memory
#SBATCH --mem=40G
# Run for five minutes
#SBATCH --time=01:00:00
# Name job
#SBATCH --job-name=SbatchJob
# Name output file
#SBATCH --output=%x_%j.out
#SBATCH --array=1-5

# change to the directory where you submitted this script
cd ${SLURM_SUBMIT_DIR}

# Executable section: echoing some Slurm data
echo "Starting sbatch script myscript.sh at:`date`"

cd /users/c/p/cpetak/CA_GRN2

#conda activate ca_grn
#echo "rule: $1"
#echo "seed: $2"

if [ $1 == "one" ]; then

  python main.py --job_array_id ${SLURM_ARRAY_TASK_ID} --rules $2 --seed_ints $3 --num_generations 10

elif [ $1 == "two" ]; then

  python main.py --job_array_id ${SLURM_ARRAY_TASK_ID} --rules $2 $3 --seed_ints $4 $5 --num_generations 10

else

  echo "specify number of alternative environments"

fi
