#!/bin/sh

#Specify a partition
#SBATCH --partition=bluemoon
# Request nodes
#SBATCH --nodes=1
# Request some processor cores
#SBATCH --ntasks=1
# Request 3 cores per task
#SBATCH --cpus-per-task=8
# Request memory
#SBATCH --mem=40G
# Run for five minutes
#SBATCH --time=30:00:00
# Name job
#SBATCH --job-name=SbatchJob
# Name output file
#SBATCH --output=%x_%j.out
#SBATCH --array=1-15

# change to the directory where you submitted this script
cd ${SLURM_SUBMIT_DIR}

# Executable section: echoing some Slurm data
echo "Starting sbatch script myscript.sh at:`date`"

cd /users/c/p/cpetak/CA_GRN2

#conda activate ca_grn
echo "task id: $SLURM_ARRAY_TASK_ID"
echo "rule1: $1"
echo "rule2: $2"
echo "seed1: $3"
echo "seed2: $4"

python main_stripped.py --job_array_id ${SLURM_ARRAY_TASK_ID} --rules $1 $2 --seed_ints $3 $4 --season_len 300  #--num_generations 3000
