#!/bin/sh

#Specify a partition
#SBATCH --partition=bluemoon
# Request nodes
#SBATCH --nodes=1
# Request some processor cores
#SBATCH --ntasks=1
# Request 3 cores per task
#SBATCH --cpus-per-task=8
# Request memory
#SBATCH --mem=40G
# Run for five minutes
#SBATCH --time=30:00:00
# Name job
#SBATCH --job-name=SbatchJob
# Name output file
#SBATCH --output=%x_%j.out
#SBATCH --array=1-5

# change to the directory where you submitted this script
cd ${SLURM_SUBMIT_DIR}

# Executable section: echoing some Slurm data
echo "Starting sbatch script myscript.sh at:`date`"

cd /users/c/p/cpetak/CA_GRN

#conda activate ca_grn
echo "rule: $1"
echo "seededness: $2"
echo "seed: $3"

python vari_env_new.py --job_array_id ${SLURM_ARRAY_TASK_ID} --seededness $2 --residual 0 --season_len 100000 --rule_combo 0 --mut_size 0.5 --pop_size 1000 --dev_steps 22 --num_generations 1000 --selection_prop 0.1  --mut_rate 0.1 --rule $1 --seedn1 $3 --seedn2 $3 --grn_size 22
